# Generated by Django 2.2.7 on 2019-11-26 05:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('morte', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sobrenome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Gênero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira um gênero (ex. Ficção científica)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(help_text='Insira o título', max_length=200)),
                ('resumo', models.TextField(help_text='Insira a descrição do título', max_length=1000)),
                ('isbn', models.CharField(help_text='<a href="http://www.isbn.bn.br/website/" target="_blank">Número do ISBN</a> de 13 caractéres', max_length=13, verbose_name='ISBN')),
                ('data_de_publicação', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Insira o autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor')),
                ('gênero', models.ManyToManyField(help_text='Insira o gênero do livro', to='catalog.Gênero')),
            ],
            options={
                'ordering': ['título', '-data_de_publicação'],
            },
        ),
        migrations.CreateModel(
            name='LivroInstância',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID do livro nesta biblioteca', primary_key=True, serialize=False)),
                ('impressão', models.CharField(max_length=200)),
                ('data_devolução', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('e', 'Emprestado'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do título', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Livro')),
            ],
            options={
                'ordering': ['data_devolução'],
            },
        ),
    ]
