# Generated by Django 2.2.7 on 2019-11-26 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191126_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gênero',
            name='nome',
            field=models.CharField(help_text='Insira um gênero (ex. Ficção científica).', max_length=200),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nome',
            field=models.CharField(help_text='Insira o idioma da versão (ex. Francês, Inglês, Japonês).', max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(help_text='Insira o autor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='gênero',
            field=models.ManyToManyField(help_text='Insira o gênero do livro.', to='catalog.Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(help_text='<a href="http://www.isbn.bn.br/website/" target="_blank">Número do ISBN</a> de 13 caractéres.', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='resumo',
            field=models.TextField(help_text='Insira a descrição do título.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='livro',
            name='título',
            field=models.CharField(help_text='Insira o título.', max_length=200),
        ),
        migrations.AlterField(
            model_name='livroinstância',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID do livro nesta biblioteca.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livroinstância',
            name='idioma',
            field=models.ManyToManyField(help_text='Insira o idioma do livro.', to='catalog.Idioma'),
        ),
    ]
