# Generated by Django 2.2.7 on 2019-11-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191126_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livroinstância',
            options={'ordering': ['data_de_devolução']},
        ),
        migrations.RenameField(
            model_name='livroinstância',
            old_name='data_devolução',
            new_name='data_de_devolução',
        ),
    ]
