# Generated by Django 2.2.7 on 2019-11-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_livroinstância_locatário'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['título', '-data_de_publicação'], 'permissions': (('pode_marcar_retornado', 'coloca o livro como retornado'),)},
        ),
    ]
