# Generated by Django 2.2.7 on 2019-11-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191129_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['título', '-data_de_publicação'], 'permissions': (('can_mark_returned', 'coloca o livro como retornado'),)},
        ),
    ]
