# Generated by Django 2.2.7 on 2019-11-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191129_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['título', '-data_de_publicação']},
        ),
        migrations.AlterModelOptions(
            name='livroinstância',
            options={'ordering': ['data_de_devolução'], 'permissions': (('can_mark_returned', 'coloca o livro como retornado'),)},
        ),
    ]
