# Generated by Django 2.2.7 on 2019-11-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191129_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livroinstância',
            options={'ordering': ['data_de_devolução'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Can set the data_de_devolução'))},
        ),
    ]
